/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project   : cbox
**     Processor : MC9S08SH32CTJ
**     Version   : Component 01.002, Driver 01.07, CPU db: 3.00.037
**     Datasheet : MC9S08SH32 Rev. 1 10/2007
**     Date/Time : 06/12/2012, 12:51 a.m.
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

/* MODULE MCUinit */

#include <mc9s08sh32.h>                /* I/O map for MC9S08SH32CTJ */
#include "MCUinit.h"

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */

#include "mytypes.h"
#include "grsens.h"
#include "grsisr.h"
#include "sci.h"
#include "maintime.h"


/* End of user declarations and definitions */


/*
** ===================================================================
**     Method      :  MCU_init (component MC9S08SH32_20)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  asm SEI;                             /* Disable interrupts */
  /* ### MC9S08SH32_20 "Cpu" init code ... */
  /*  PE initialization code after reset */

  /* Common initialization of the write once registers */
  /* SOPT1: COPT=0,STOPE=0,IICPS=0,BKGDPE=1,RSTPE=0 */
  SOPT1 = 2;                                      
  /* SOPT2: COPCLKS=0,COPW=0,ACIC=0,T2CH1PS=0,T2CH0PS=0,T1CH1PS=0,T1CH0PS=0 */
  SOPT2 = 0;                                      
  /* SPMSC1: LVWF=0,LVWACK=0,LVWIE=0,LVDRE=1,LVDSE=1,LVDE=0,BGBE=0 */
  SPMSC1 = 24;                                      
  /* SPMSC2: LVDV=0,LVWV=0,PPDF=0,PPDACK=0,PPDC=0 */
  SPMSC2 = 0;                                      
  /*  System clock initialization */
  if (*(unsigned char*far)65455 != 255) { /* Test if the device trim value is stored on the specified address */
    ICSTRM = *(unsigned char*far)65455; /* Initialize ICSTRM register from a non volatile memory */
    ICSSC = *(unsigned char*far)65454; /* Initialize ICSSC register from a non volatile memory */
  }
  /* ICSC1: CLKS=0,RDIV=7,IREFS=0,IRCLKEN=0,IREFSTEN=0 */
  ICSC1 = 56;                          /* Initialization of the ICS control register 1 */
  /* ICSC2: BDIV=0,RANGE=1,HGO=0,LP=0,EREFS=1,ERCLKEN=1,EREFSTEN=0 */
  ICSC2 = 38;                          /* Initialization of the ICS control register 2 */
  while(!ICSSC_OSCINIT) {              /* Wait until the initialization of the external crystal oscillator is completed */
  }
  /* GNGC: GNGPS7=0,GNGPS6=0,GNGPS5=0,GNGPS4=0,GNGPS3=0,GNGPS2=0,GNGPS1=0,GNGEN=0 */
  GNGC = 0;                                      
  /* Common initialization of the CPU registers */
  /* PTBPE: PTBPE4=0 */
  PTBPE &= (unsigned char)~16;                     
  /* PTASE: PTASE4=0,PTASE3=0,PTASE2=0,PTASE1=0,PTASE0=0 */
  PTASE &= (unsigned char)~31;                     
  /* PTBSE: PTBSE7=0,PTBSE6=0,PTBSE5=0,PTBSE4=0,PTBSE3=0,PTBSE2=0,PTBSE1=0,PTBSE0=0 */
  PTBSE = 0;                                      
  /* PTCSE: PTCSE3=0,PTCSE2=0,PTCSE1=0,PTCSE0=0 */
  PTCSE &= (unsigned char)~15;                     
  /* PTADS: PTADS7=0,PTADS6=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 */
  PTADS = 0;                                      
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
  PTBDS = 0;                                      
  /* PTCDS: PTCDS7=0,PTCDS6=0,PTCDS5=0,PTCDS4=0,PTCDS3=0,PTCDS2=0,PTCDS1=0,PTCDS0=0 */
  PTCDS = 0;                                      
  /* ### Init_TPM init code */
  (void)(TPM2C1SC == 0);               /* Channel 0 int. flag clearing (first part) */
  /* TPM2C1SC: CH1F=0,CH1IE=1,MS1B=0,MS1A=0,ELS1B=0,ELS1A=1 */
  TPM2C1SC = 68;                       /* Int. flag clearing (2nd part) and channel 0 contr. register setting */
  /* TPM2SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=0,CLKSA=0,PS2=0,PS1=0,PS0=0 */
  TPM2SC = 0;                          /* Stop and reset counter */
  TPM2MOD = 0U;                        /* Period value setting */
  (void)(TPM2SC == 0);                 /* Overflow int. flag clearing (first part) */
  /* TPM2SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=1,CLKSA=0,PS2=1,PS1=0,PS0=0 */
  TPM2SC = 20;                         /* Int. flag clearing (2nd part) and timer control register setting */
  /* ### Init_GPIO init code */
  /* PTCD: PTCD3=0,PTCD2=0 */
  PTCD &= (unsigned char)~12;                     
  /* PTCPE: PTCPE3=1,PTCPE2=1,PTCPE1=1 */
  PTCPE |= (unsigned char)14;                      
  /* PTCDD: PTCDD3=0,PTCDD2=0,PTCDD1=0 */
  PTCDD &= (unsigned char)~14;                     
  /* ### Init_MTIM init code */
  /* MTIMMOD: MOD7=0,MOD6=0,MOD5=0,MOD4=0,MOD3=0,MOD2=0,MOD1=0,MOD0=0 */
  MTIMMOD = 0;                                      
  /* MTIMCLK: CLKS1=0,CLKS0=0,PS3=0,PS2=1,PS1=1,PS0=0 */
  MTIMCLK = 6;                                      
  (void)(MTIMSC == 0);                 /* Overflow int. flag clearing (first part) */
  /* MTIMSC: TOF=0,TOIE=1,TRST=1,TSTP=0 */
  MTIMSC = 96;                         /* Int. flag clearing (2nd part) and timer control register setting */
  /* ### Init_ADC init code */
  /* APCTL1: ADPC7=0,ADPC6=0,ADPC5=0,ADPC4=0,ADPC3=0,ADPC2=0,ADPC1=0,ADPC0=1 */
  APCTL1 = 1;                                      
  /* APCTL2: ADPC15=0,ADPC14=0,ADPC13=0,ADPC12=0,ADPC11=0,ADPC10=0,ADPC9=0,ADPC8=1 */
  APCTL2 = 1;                                      
  /* ADCCFG: ADLPC=0,ADIV1=1,ADIV0=0,ADLSMP=0,MODE1=0,MODE0=0,ADICLK1=0,ADICLK0=0 */
  ADCCFG = 64;                                      
  /* ADCCV: ADCV9=0,ADCV8=0,ADCV7=0,ADCV6=0,ADCV5=0,ADCV4=0,ADCV3=0,ADCV2=0,ADCV1=0,ADCV0=0 */
  ADCCV = 0U;                            
  /* ADCSC2: ADACT=0,ADTRG=0,ACFE=0,ACFGT=0 */
  ADCSC2 = 0;                                      
  /* ADCSC1: COCO=0,AIEN=0,ADCO=0,ADCH4=0,ADCH3=0,ADCH2=0,ADCH1=0,ADCH0=0 */
  ADCSC1 = 0;                                      
  /* ### Init_SCI init code */
  /* SCIC2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  SCIC2 = 0;                           /* Disable the SCI module */
  (void)(SCIS1 == 0);                  /* Dummy read of the SCIS1 register to clear flags */
  (void)(SCID == 0);                   /* Dummy read of the SCID register to clear flags */
  /* SCIS2: LBKDIF=1,RXEDGIF=1,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  SCIS2 = 192;                                      
  /* SCIBDH: LBKDIE=0,RXEDGIE=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0 */
  SCIBDH = 0;                                      
  /* SCIBDL: SBR7=0,SBR6=0,SBR5=0,SBR4=0,SBR3=0,SBR2=1,SBR1=0,SBR0=0 */
  SCIBDL = 4;                                      
  /* SCIC1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  SCIC1 = 0;                                      
  /* SCIC3: R8=0,T8=0,TXDIR=0,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  SCIC3 = 0;                                      
  /* SCIC2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  SCIC2 = 0;                                      
  /* ### Init_GPIO init code */
  /* PTBD: PTBD5=0,PTBD3=0,PTBD2=0 */
  PTBD &= (unsigned char)~44;                     
  /* PTBDD: PTBDD5=1,PTBDD3=1,PTBDD2=1 */
  PTBDD |= (unsigned char)44;                      
  /* ### Init_GPIO init code */
  /* PTAD: PTAD1=1 */
  PTAD |= (unsigned char)2;                      
  /* PTADD: PTADD1=1 */
  PTADD |= (unsigned char)2;                      
  /* ### */
} /*MCU_init*/


/*
** ===================================================================
**     Interrupt handler : isrVmtim
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVmtim(void)
{
  /* Write your interrupt code here ... */
	MTIMSC &= ~0x80;
	main_timer_interrupt();
}
/* end of isrVmtim */


/*
** ===================================================================
**     Interrupt handler : isrVadc
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVadc(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVadc */





/*
** ===================================================================
**     Interrupt handler : isrVscierr
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVscierr(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVscierr */


/*
** ===================================================================
**     Interrupt handler : isrVtpm2ovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtpm2ovf(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVtpm2ovf */


/*
** ===================================================================
**     Interrupt handler : isrVtpm2ch1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtpm2ch1(void)
{
	unsigned short count;
	/* Write your interrupt code here ... */
	TPM2C1SC &= ~0x80;				// acknowledge interrupt

	if( (TPM2C1SC & 0x0C) == 0x04 ) // if next detect is rising edge
		TPM2CNTH = 0;				// reset timer counter
  	else
	{
		count = TPM2C1V;			// get timer count
		grs_sample_isr( (unsigned char)count );
	}
	
	TPM2C1SC ^= 0x0C;				// change edge polarity detection
}
/* end of isrVtpm2ch1 */



/* Initialization of the CPU registers in FLASH */

/* NVPROT: FPS7=1,FPS6=1,FPS5=1,FPS4=1,FPS3=1,FPS2=1,FPS1=1,FPDIS=1 */
const unsigned char NVPROT_INIT @0x0000FFBD = 255;

/* NVOPT: KEYEN=0,FNORED=1,SEC01=1,SEC00=0 */
const unsigned char NVOPT_INIT @0x0000FFBF = 126;



extern near void _Startup(void);

/* Interrupt vector table */
#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR ((void(*near const)(void)) 0xFFFF) /* unassigned interrupt service routine */
#endif

void (* near const _vect[])(void) @0xFFC0 = { /* Interrupt vector table */
         UNASSIGNED_ISR,               /* Int.no. 31 VReserved31 (at FFC0)           Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 30 Vacmp (at FFC2)                 Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 29 VReserved29 (at FFC4)           Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 28 VReserved28 (at FFC6)           Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 27 VReserved27 (at FFC8)           Unassigned */
         isrVmtim,                     /* Int.no. 26 Vmtim (at FFCA)                 Used */
         UNASSIGNED_ISR,               /* Int.no. 25 Vrtc (at FFCC)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 24 Viic (at FFCE)                  Unassigned */
         isrVadc,                      /* Int.no. 23 Vadc (at FFD0)                  Used */
         UNASSIGNED_ISR,               /* Int.no. 22 VReserved22 (at FFD2)           Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 21 Vportb (at FFD4)                Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 20 Vporta (at FFD6)                Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 19 VReserved19 (at FFD8)           Unassigned */
         host_xmit_isr,                /* Int.no. 18 Vscitx (at FFDA)                Used */
         host_rcv_isr,                 /* Int.no. 17 Vscirx (at FFDC)                Used */
         isrVscierr,                   /* Int.no. 16 Vscierr (at FFDE)               Used */
         UNASSIGNED_ISR,               /* Int.no. 15 Vspi (at FFE0)                  Unassigned */
         isrVtpm2ovf,                  /* Int.no. 14 Vtpm2ovf (at FFE2)              Used */
         isrVtpm2ch1,                  /* Int.no. 13 Vtpm2ch1 (at FFE4)              Used */
         UNASSIGNED_ISR,               /* Int.no. 12 Vtpm2ch0 (at FFE6)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 11 Vtpm1ovf (at FFE8)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 10 VReserved10 (at FFEA)           Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  9 VReserved9 (at FFEC)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  8 VReserved8 (at FFEE)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  7 VReserved7 (at FFF0)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  6 Vtpm1ch1 (at FFF2)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  5 Vtpm1ch0 (at FFF4)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  4 VReserved4 (at FFF6)            Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _Startup                      /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};





/*
** ===================================================================
**     Interrupt handler : isrVrtc
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVrtc(void)
{
  /* Write your interrupt code here ... */
	RTCSC &= 0x80;
}
/* end of isrVrtc */

/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
